/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mateamina.ui.internal.MateaminaActivator;

public class MathLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MateaminaActivator.getInstance().getInjector("org.xtext.example.mathlang.MathLang");
	}

}
