/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.mathLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delimited Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mathlang.mathLang.DelimitedExpr#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getDelimitedExpr()
 * @model
 * @generated
 */
public interface DelimitedExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getDelimitedExpr_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mathlang.mathLang.DelimitedExpr#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // DelimitedExpr
