/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.mathLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negative</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mathlang.mathLang.Negative#getOperand <em>Operand</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getNegative()
 * @model
 * @generated
 */
public interface Negative extends Expression
{
  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference.
   * @see #setOperand(Expression)
   * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getNegative_Operand()
   * @model containment="true"
   * @generated
   */
  Expression getOperand();

  /**
   * Sets the value of the '{@link org.xtext.example.mathlang.mathLang.Negative#getOperand <em>Operand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand</em>' containment reference.
   * @see #getOperand()
   * @generated
   */
  void setOperand(Expression value);

} // Negative
