/**
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.mathLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mathlang.mathLang.Pow#getBase <em>Base</em>}</li>
 *   <li>{@link org.xtext.example.mathlang.mathLang.Pow#getExponent <em>Exponent</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getPow()
 * @model
 * @generated
 */
public interface Pow extends Expression
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' containment reference.
   * @see #setBase(Expression)
   * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getPow_Base()
   * @model containment="true"
   * @generated
   */
  Expression getBase();

  /**
   * Sets the value of the '{@link org.xtext.example.mathlang.mathLang.Pow#getBase <em>Base</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' containment reference.
   * @see #getBase()
   * @generated
   */
  void setBase(Expression value);

  /**
   * Returns the value of the '<em><b>Exponent</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exponent</em>' containment reference.
   * @see #setExponent(Expression)
   * @see org.xtext.example.mathlang.mathLang.MathLangPackage#getPow_Exponent()
   * @model containment="true"
   * @generated
   */
  Expression getExponent();

  /**
   * Sets the value of the '{@link org.xtext.example.mathlang.mathLang.Pow#getExponent <em>Exponent</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exponent</em>' containment reference.
   * @see #getExponent()
   * @generated
   */
  void setExponent(Expression value);

} // Pow
