/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.arithmetic.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArithmeticScopeProvider extends DelegatingScopeProvider {
}
