/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.arithmetic.ide;


/**
 * Use this class to register ide components.
 */
public class ArithmeticIdeModule extends AbstractArithmeticIdeModule {
}
