/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mathlang.parser.antlr.internal.InternalMathLangParser;
import org.xtext.example.mathlang.services.MathLangGrammarAccess;

public class MathLangParser extends AbstractAntlrParser {

	@Inject
	private MathLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMathLangParser createParser(XtextTokenStream stream) {
		return new InternalMathLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MathLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
