/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathLangScopeProvider extends DelegatingScopeProvider {
}
