/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.arithmetic.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.arithmetic.ui.internal.ArithmeticActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArithmeticExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ArithmeticActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ArithmeticActivator activator = ArithmeticActivator.getInstance();
		return activator != null ? activator.getInjector(ArithmeticActivator.ORG_XTEXT_EXAMPLE_ARITHMETIC_ARITHMETIC) : null;
	}

}
