/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.arithmetic.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.arithmetic.ui.internal.ArithmeticActivator;

public class ArithmeticUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ArithmeticActivator.getInstance().getInjector("org.xtext.example.arithmetic.Arithmetic");
	}

}
