/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.ide;


/**
 * Use this class to register ide components.
 */
public class MathLangIdeModule extends AbstractMathLangIdeModule {
}
