/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mathlang.MathLangRuntimeModule;
import org.xtext.example.mathlang.MathLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MathLangIdeSetup extends MathLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MathLangRuntimeModule(), new MathLangIdeModule()));
	}
	
}
