/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathLangStandaloneSetup extends MathLangStandaloneSetupGenerated {

	public static void doSetup() {
		new MathLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
