/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MathLangUiModule extends AbstractMathLangUiModule {

	public MathLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
