/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.mathlang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mateamina.ui.internal.MateaminaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MateaminaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MateaminaActivator activator = MateaminaActivator.getInstance();
		return activator != null ? activator.getInjector(MateaminaActivator.ORG_XTEXT_EXAMPLE_MATHLANG_MATHLANG) : null;
	}

}
